baseURL: 'http://localhost:5000'
languageCode: 'en-us'
title: 'Building CNS 2.0: A Developer''s Guide'
disableKinds: ['sitemap']

params:
  description: 'A progressive educational guide to implementing Chiral Narrative Synthesis 2.0 in Python'
  author: 'CNS Development Team'
  
markup:
  goldmark:
    renderer:
      unsafe: true
    extensions:
      passthrough:
        enable: true
        delimiters:
          block: [['$$', '$$']]
          inline: [['$', '$']]
  # highlight:
  #   style: vs2015
  #   lineNos: true
  #   lineNumbersInTable: true
  #   tabWidth: 4

menu:
  main:
    - name: "Introduction"
      url: "/guides/building-cns-2.0-developers-guide/chapter-1-introduction/"
      weight: 1
    - name: "SNO Foundations"
      url: "/guides/building-cns-2.0-developers-guide/chapter-2-sno-foundations/"
      weight: 2
    - name: "Critic Pipeline"
      url: "/guides/building-cns-2.0-developers-guide/chapter-3-critic-pipeline/"
      weight: 3
    - name: "Synthesis Engine"
      url: "/guides/building-cns-2.0-developers-guide/chapter-4-synthesis-engine/"
      weight: 4
    - name: "System Integration"
      url: "/guides/building-cns-2.0-developers-guide/chapter-5-system-integration/"
      weight: 5
    - name: "Complete Implementation"
      url: "/guides/building-cns-2.0-developers-guide/chapter-6-complete-implementation/"
      weight: 6
    - name: "DSPy Integration"
      url: "/guides/building-cns-2.0-developers-guide/chapter-7-dspy-integration/"
      weight: 7

server:
  host: '0.0.0.0'
  port: 5000

staticDir: 'static'
disableKinds: ['home', 'taxonomy', 'term']

# Make sure static files take precedence
uglyURLs: false
relativeURLs: false

# Prioritize static files
staticDirs: ['static']
publishDir: 'public'
