baseURL: 'http://localhost:5000'
languageCode: 'en-us'
title: 'CNS 2.0 Project'

params:
  description: 'A progressive educational guide to implementing Chiral Narrative Synthesis 2.0 in Python'
  author: 'CNS Development Team'
  
markup:
  goldmark:
    renderer:
      unsafe: true
    extensions:
      passthrough:
        enable: true
        delimiters:
          block: [['$$', '$$']]
          inline: [['$', '$']]
  # highlight:
  #   style: vs2015
  #   lineNos: true
  #   lineNumbersInTable: true
  #   tabWidth: 4

menu:
  main:
    - name: "Overview"
      identifier: "overview"
      url: "/overview/"
      weight: 0
    - name: "Developer's Guide"
      identifier: "devguide"
      url: "/guides/building-cns-2.0-developers-guide/"
      weight: 1
    - name: "Research Roadmap"
      identifier: "research"
      url: "/guides/cns-2.0-research-roadmap/"
      weight: 2
    - name: "Theoretical Foundations"
      identifier: "theory"
      url: "/theoretical-foundations/"
      weight: 3
    - name: "Ethics & Responsibility"
      identifier: "ethics"
      url: "/ethics/"
      weight: 4
    - name: "Blueprint Paper"
      identifier: "blueprint"
      url: "/blueprint/"
      weight: 5

server:
  host: '0.0.0.0'
  port: 5000

staticDir: 'static'
disableKinds: ['home', 'taxonomy', 'term']

# Make sure static files take precedence
uglyURLs: false
relativeURLs: false

# Prioritize static files
staticDirs: ['static']
publishDir: 'public'
